#!/bin/bash

# Perform RMAN backup
# Expected usage: f_perform_backup DB LEVEL
#  DB: Database SID to pass to RMAN
#  LEVEL: full/inc - full is full incremental, inc is differential incremental
f_perform_backup() {
  export LEVEL="$1"
  echo "Performing backup on $ORACLE_SID."
  echo "Performing $LEVEL backup."
  export DATE = $(date +% y -% m -% d_ % H % M % S)

  # Run RMAN
  $ORACLE_HOME/bin/rman <<RMAN
    connect target /
    run {
      delete noprompt obsolete;
      allocate channel d1 device type disk format '/db01/backup/%U';
      backup
      incremental level = $LEVEL
      database include current controlfile;
      backup archivelog all delete input;
    }
    exit;
RMAN
  echo "backup completed on $ORACLE_SID, at: $(date)"
}

# Main
# Expected usage: ./backup_db DBNAME BACKUP_TYPE
#  DBNAME: SID of Oracle database
#  BACKUP_TYPE: Incremental backup, or full backup
f_main() {
  echo "ORACLE_HOME set to: $ORACLE_HOME"
  if [ -z "$ORACLE_HOME" ]; then
    echo "\$ORACLE_HOME isn't set. Exiting."
    exit 133
  fi
  # which database?
  if [ -z "$1" ]; then
    echo "\$ORACLE_SID not provided. Exiting."
    exit 133
  else
    export ORACLE_SID=$1
  fi
  # incremental or full?
  if [ -z "$2" ]; then
    echo "No backup method specified. Exiting."
    exit 133
  else
    if [ "$2" == "inc" ]; then
      f_perform_backup "1"
    elif [ "$2" == "full" ]; then
      f_perform_backup "0"
    else
      echo "Invalid backup method specified. Exiting."
    fi
  fi
}

# Source environment
source $HOME/.bash_profile

# Colors
RESTORE='\033[0m'
PURPLE='\033[00;35m'

# Call main, pass parameters
echo "Running script on: $(date)."
f_main "$1" "$2"
cat: AMSPRD1: No such file or directory









CONFIGURE CONTROLFILE AUTOBACKUP FORMAT FOR DEVICE TYPE DISK TO '/db01/backup/dg_backup/%F';
CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT   '/db01/backup/dg_backup/%U';

using target database control file instead of recovery catalog
RMAN configuration parameters for database with db_unique_name AMSPRD are:
CONFIGURE RETENTION POLICY TO REDUNDANCY 1; # default
CONFIGURE BACKUP OPTIMIZATION OFF; # default
CONFIGURE DEFAULT DEVICE TYPE TO DISK; # default
CONFIGURE CONTROLFILE AUTOBACKUP ON; # default
CONFIGURE CONTROLFILE AUTOBACKUP FORMAT FOR DEVICE TYPE DISK TO '/db01/backup/dg_backup/%F';
CONFIGURE DEVICE TYPE DISK PARALLELISM 1 BACKUP TYPE TO BACKUPSET; # default
CONFIGURE DATAFILE BACKUP COPIES FOR DEVICE TYPE DISK TO 4;
CONFIGURE ARCHIVELOG BACKUP COPIES FOR DEVICE TYPE DISK TO 1; # default
CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT   '/db01/backup/dg_backup/%U';
CONFIGURE MAXSETSIZE TO UNLIMITED; # default
CONFIGURE ENCRYPTION FOR DATABASE OFF; # default
CONFIGURE ENCRYPTION ALGORITHM 'AES128'; # default
CONFIGURE COMPRESSION ALGORITHM 'BASIC' AS OF RELEASE 'DEFAULT' OPTIMIZE FOR LOAD TRUE ; # default
CONFIGURE RMAN OUTPUT TO KEEP FOR 3 DAYS;
CONFIGURE ARCHIVELOG DELETION POLICY TO NONE; # default
CONFIGURE SNAPSHOT CONTROLFILE NAME TO '+BACKUP/amsprd/backupset/snapcf_AMSPRD1.f';

